/** @type {import('tailwindcss').Config} */
module.exports = {
  // Use class strategy for dark mode – ThemeProvider toggles "dark" class on <html>
  darkMode: 'class',
  // Tailwind scans source files for class names
  content: [
    './src/**/*.{js,jsx,ts,tsx,html,css}',
  ],
  theme: {
    extend: {
      // Register CSS variables as Tailwind colors so @apply works with them
      colors: {
        'app-bg': 'var(--app-bg)',
        'app-text': 'var(--app-text)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'surface': 'var(--surface)',
        'surface-alt': 'var(--surface-alt)',
        'surface-glass': 'var(--surface-glass)',
        'surface-glass-strong': 'var(--surface-glass-strong)',
        'surface-input': 'var(--surface-input)',
        'surface-hover': 'var(--surface-hover)',
        'surface-active': 'var(--surface-active)',
        'header-bg': 'var(--header-bg)',
        'header-border': 'var(--header-border)',
        'footer-bg': 'var(--footer-bg)',
        'overlay': 'var(--overlay)',
        'accent-cyan': 'var(--accent-cyan)',
        'btn-primary-bg': 'var(--btn-primary-bg)',
        'btn-primary-text': 'var(--btn-primary-text)',
        'chip-bg': 'var(--chip-bg)',
        'chip-hover-bg': 'var(--chip-hover-bg)',
        'grid-line': 'var(--grid-line)',
        'section-tint': 'var(--section-tint)',
        'border': 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'border-subtle': 'var(--border-subtle)',
        'border-blue': 'var(--border-blue)',
        'border-cyan': 'var(--border-cyan)',
        'bg': 'var(--bg)',
        'panel': 'var(--panel)',
        'card': 'var(--card)',
        'card-raised': 'var(--card-raised)',
        'text': 'var(--text)',
        'muted': 'var(--muted)',
        'faint': 'var(--faint)',
        'faint-2': 'var(--faint-2)',
        'cyan': 'var(--cyan)',
        'primary': 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        'primary-soft': 'var(--primary-soft)',
        'primary-dim': 'var(--primary-dim)',
        'focus-glow': 'var(--focus-glow)',
        'mint-soft': 'var(--mint-soft)',
        'red-soft': 'var(--red-soft)',
        'section-glow': 'var(--section-glow)',
        'mint': 'var(--mint)',
        'lavender': 'var(--lavender)',
        'red': 'var(--red)',
        'green': 'var(--green)',
        'popover': 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        'background': 'var(--background)',
        'foreground': 'var(--foreground)',
        'secondary': 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        'muted-foreground': 'var(--muted-foreground)',
        'accent': 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        'destructive': 'var(--destructive)',
        'input': 'var(--input)',
        'ring': 'var(--ring)',
      },
      // Preserve custom radius values for shadcn UI components
      borderRadius: {
        sm: 'calc(var(--radius) * 0.6)',
        md: 'calc(var(--radius) * 0.8)',
        lg: 'var(--radius)',
        xl: 'calc(var(--radius) * 1.4)',
        '2xl': 'calc(var(--radius) * 1.8)',
        '3xl': 'calc(var(--radius) * 2.2)',
        '4xl': 'calc(var(--radius) * 2.6)',
      },
    },
  },
  plugins: [],
};
